services:
    _defaults:
        autowire: true
        autoconfigure: true

    lightsaml.profile.metadata:
        class: LightSaml\Builder\Profile\Metadata\MetadataProfileBuilder
        public: true
        arguments:
            - "@lightsaml.container.build"

    lightsaml.profile.login_factory:
        class: LightSaml\Builder\Profile\WebBrowserSso\Sp\SsoSpSendAuthnRequestProfileBuilderFactory
        public: true
        arguments:
            - "@lightsaml.container.build"

    lightsaml.profile.acs:
        class: LightSaml\Builder\Profile\WebBrowserSso\Sp\SsoSpReceiveResponseProfileBuilder
        public: true
        arguments:
            - "@lightsaml.container.build"
